---
title: "MAGiC ROC-related results"
output: html_notebook
---


```{r}
# import required packages
library(nnet)
library(multiROC)
library(readxl)
library(ggplot2)
library(pROC)
library(stringr)
library(outliers)


df1 <- read_excel("./Qvalues_0830.xlsx", sheet = "Sheet1")
df2 <- read_excel("./Qvalues_0830.xlsx", sheet = "Sheet2")

df <- df1
df[, 2:9] <- (df1[, 2:9] + df2[, 2:9])/2

set.seed(42)

summary_def <- function(x,na.omit=FALSE){
  if(na.omit)
    x <- x[!is.na(x)]
  m <- mean(x)
  n <- length(x)
  s <- sd(x)
  min_x <- min(x)
  max_x <- max(x)
  return(c(n=n,mean=m,stdev=s,min=min_x,max=max_x))
}


# df_input: df; y: "LVSI"; x: list("T1", "T2")
auc_2l <- function(df_input, y, x){
  # string to formula
  f <- paste(y, "~", paste(x, collapse=" + "))
  # string to vector
  columns = as.vector(unlist(x))
  columns = append(columns, y)
  # update df
  df_new = df_input[complete.cases(df_input[, columns]), ]
  df_new[[y]] = as.factor(df_new[[y]])
   
  model = glm(f, data = df_new, family = binomial(logit))
  roc_df = roc(model$y, model$fitted.values, ci=T)
  print(roc_df$auc)
  return(roc_df)
}


# y: "Grade"; x: list("T1", "T2"); encode_level: c("1a", "1b", "o")
auc_3l <- function(df_input, y, x){
  # string to formula
  f <- paste(y, "~", paste(x, collapse=" + "))
  # string to vector
  columns = as.vector(unlist(x))
  columns = append(columns, y)
  # update df
  df_new = df_input[complete.cases(df_input[, columns]), ]
  df_new[[y]] = as.factor(df_new[[y]])
  
  mnl_3c = multinom(f, data = df_new)
  #chisq.test(as.factor(df$Grade), predict(a))
  #table(as.factor(df$Grade), predict(a))

  # prepare dataframe for multiROC
  df_roc = data.frame("NO" = df_new$NO)
  # one-hot encoding
  df_new$gra_enc = factor(df_new[[y]], ordered = T, levels = mnl_3c$lev)
  true_1h = model.matrix(~gra_enc-1, df_new)
  # rename dataframe
  df_roc$C1_true = true_1h[, 1]
  df_roc$C2_true = true_1h[, 2]
  df_roc$C3_true = true_1h[, 3]
  df_roc$C1_pred_mnl = mnl_3c$fitted.values[, 1]
  df_roc$C2_pred_mnl = mnl_3c$fitted.values[, 2]
  df_roc$C3_pred_mnl = mnl_3c$fitted.values[, 3]
  # calculate AUC
  pr_test = multi_pr(df_roc)
  print(pr_test$AUC)
  return(pr_test)
}


auc_prep <- function(df_input, y, x) {
  # string to formula
  f <- paste(y, "~", paste(x, collapse=" + "))
  # string to vector
  columns = as.vector(unlist(x))
  columns = append(columns, y)
  # update df
  df_new = df_input[complete.cases(df_input[, columns]), ]
  df_new[[y]] = as.factor(df_new[[y]])
   
  model = glm(f, data = df_new, family = binomial(logit))
  return(list(y = model$y, pred = model$fitted.values))
}
```


```{r}
# add a new column 
df1 = transform(df, MI2=0)
# pick out cases with MI1-2
list_high = which(df$MI > 0); 
# no MI: 0; MI: 1;
df1[list_high, 'MI2'] = 1 

result1 = auc_prep(df1, "MI2", list("T2", "PD","ADC"))
```



```{r G1 vs. G2-G3}
# add a new column 
df1 = transform(df, gra2=0)
# pick out cases with G2-3
list_g3 = which(df$Grade > 1); 
# G1: 0; G2-3: 1;
df1[list_g3, 'gra2'] = 1 

result2 = auc_prep(df1, "gra2", list("ADC"))
```


```{r}
result3 = auc_prep(df, "LVSI", list("ADC"))
```


```{r}
y = c(result1$y, result2$y, result3$y)
pred = c(result1$pred, result2$pred, result3$pred)

roc1 = roc(result1$y, result1$pred, ci=T)
roc2 = roc(result2$y, result2$pred, ci=T)
roc3 = roc(result3$y, result3$pred, ci=T)
roc0 = roc(y, pred, ci=T)
```



```{r}
roc_list = list("MI" = roc1, "Grade" = roc2, "LVSI" = roc3, "Micro Average" = roc0)
AUCs = c(roc1$auc, roc2$auc, roc3$auc, roc0$auc)
names = c("MI", "Grade", "LVSI", "Micro Average")
roc_labels = paste0(names,", AUC=", paste(round(AUC, 2)))

ggroc(roc_list, aes = 'color', legacy.axes = T, size = 1.5) + 
  scale_color_discrete(labels=roc_labels) +
  theme(legend.position=c(0.75,0.25)) +
  labs(color="Parameters")

ggsave("roc.tiff", units="in", width = 6, height = 6, dpi = 400, compression="lzw")
```

